[profile.default]
src = "src/0.8.25"
out = 'out'
test = 'test/0.8.25'
solc_version = '0.8.25'
auto_detect_solc = false
optimizer_runs = 10_000
libs = [
  'node_modules',
    'lib'
]
auto_detect_remappings = false
fuzz = { runs = 1000 }

[profile.ci]
  fuzz = { runs = 1_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 132
  multiline_func_header = "all"
  number_underscore = "preserve"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[profile.0_8_20]
src = 'src/0.8.20'
out = 'out'
test = 'test/0.8.20'
libs = ['node_modules','lib']
vm_version='shanghai'
optimizer_runs = 10_000
auto_detect_remappings = false
solc_version = '0.8.20'