[profile.default]
src = "src"
out = 'out'
test = 'test-foundry'
solc_version = '0.8.20'
auto_detect_solc = false
optimizer_runs = 10_000
libs = [
  'node_modules',
    'lib'
]
remappings = [
    'solidity-rlp/=lib/Solidity-RLP/contracts/',
    'murky/=lib/murky/src/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
]
auto_detect_remappings = false
fuzz = { runs = 10000 }

[profile.ci]
  fuzz = { runs = 1_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 132
  multiline_func_header = "all"
  number_underscore = "preserve"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true